version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fe
      - be
    networks:
      - appnet

networks:
  appnet:
    driver: bridge