version: '3.8'
services:
  fe:
    build: ./my-portfolio
    container_name: fe
    restart: always
    networks:
      - fe-network
    ports:
      - "3000:3000"

volumes:
  pgdata:

networks:
  fe-network:
    external: true