version: '3.8'
services:
  fe:
    build: ./my-portfolio
    container_name: fe
    restart: always
    networks:
      - appnet
    ports:
      - "3000:3000"

  be:
    build: ./my-portfolio-backend
    container_name: be
    restart: always
    networks:
      - appnet
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fe
      - be
    networks:
      - appnet

networks:
  appnet:
    driver: bridge