version: '3.8'
services:
  fe:
    build: ./my-portfolio
    container_name: fe
    restart: always
    networks:
      - appnet
    ports:
      - "3000:3000"

  be:
    build: ./my-portfolio-backend
    container_name: be
    restart: always
    networks:
      - appnet
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fe
      - be
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge