name: Deploy Backend

on:
  push:
    paths:
      - 'my-portfolio-backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Create remote directory if not exists
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /home/${{ secrets.VPS_USER }}/nextjs-app/my-portfolio-backend"

      - name: Copy files to VPS.
        run: |
          rsync -avz --delete ./my-portfolio-backend ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/nextjs-app

      - name: Build & run Docker on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ../home/root/nextjs-app
            docker compose down be || true 
            docker compose up -d be --build
          EOF

      - name: Build backend before EF update
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/${{ secrets.VPS_USER }}/nextjs-app/my-portfolio-backend
            dotnet build
          EOF

      - name: Run EF database update
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/${{ secrets.VPS_USER }}/nextjs-app/my-portfolio-backend
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install --global dotnet-ef || true
            dotnet ef database update
          EOF