name: Deploy Next.js to VPS

on:
  push:
    paths:
      - 'my-portfolio/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    paths:
      - 'my-portfolioe/**'
      - '.github/workflows/deploy.yml'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Create remote directory if not exists
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /home/${{ secrets.VPS_USER }}/nextjs-app"

      - name: Copy files to VPS
        run: |
          rsync -avz --delete --exclude '.git' ./my-portfolio/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/nextjs-app

      - name: Copy docker-compose.yml
        run: |
          rsync -avz ./docker-compose.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/nextjs-app/docker-compose.yml

      - name: Build & run Docker on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ../home/${{ secrets.VPS_USER }}/nextjs-app
            docker compose -f docker-compose.yml -f docker-compose.fe.yml build fe
            docker compose -f docker-compose.yml -f docker-compose.fe.yml up -d fe
          EOF